package formularios;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTextField;
import operacionesCliente.ABMCliente;
import clasesUtilidadGeneral.OperacionesUtiles;
import escritorios.PrincipalCliente;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import operacionesCliente.InterfazGraficaFormularioRegistrarCliente;
import operacionesCliente.TablaCliente;
import operacionesCliente.TecladoInterfaz;
import principal.MaterialButton;
import rojeru_san.componentes.RSDateChooser;

/**
 *
 * @author TELCOM MPC
 */
public class FormularioRegistrarCliente extends javax.swing.JDialog {

    int x, y;
    private ABMCliente abm = new ABMCliente();

    PrincipalCliente principalCliente;

    public PrincipalCliente getPrincipalCliente() {
        return principalCliente;
    }

    public void setPrincipalCliente(PrincipalCliente principalCliente) {
        this.principalCliente = principalCliente;
    }

    /**
     * Creates new form FormularioNuevoCliente
     */
    public FormularioRegistrarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public List getListaCampos() {
        List listCamposTexto = new ArrayList();
        listCamposTexto.add(this.getTxtNombre());
        listCamposTexto.add(this.getTxtApellido());
        listCamposTexto.add(this.getTxtTelefono());

        return listCamposTexto;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public void setTxtApellido(JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public JPanel getPanelPrincipalTop() {
        return panelPrincipalTop;
    }

    public void setPanelPrincipalTop(JPanel panelPrincipalTop) {
        this.panelPrincipalTop = panelPrincipalTop;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelPrincipalTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelPrincipalBody = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnCancelar = new principal.MaterialButton();
        btnRegistrar = new principal.MaterialButton();
        boxEmpresa = new javax.swing.JComboBox<>();
        boxTipoSeguro = new javax.swing.JComboBox<>();
        txtNumeroPoliza = new javax.swing.JTextField();
        txtDominio = new javax.swing.JTextField();
        boxProvincia = new javax.swing.JComboBox<>();
        boxLocalidad = new javax.swing.JComboBox<>();
        txtDireccion = new javax.swing.JTextField();
        txtNroDireccion = new javax.swing.JTextField();
        txtNroDNI = new javax.swing.JTextField();
        radioBtnFemenino = new javax.swing.JRadioButton();
        radioBtnMasculino = new javax.swing.JRadioButton();
        radioBtnOtros = new javax.swing.JRadioButton();
        rSDateChooser = new rojeru_san.componentes.RSDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panelBase.setBackground(new java.awt.Color(255, 255, 255));
        panelBase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), java.awt.Color.gray, new java.awt.Color(102, 102, 102), java.awt.Color.gray));

        panelPrincipalTop.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRAR CLIENTE");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new80.png"))); // NOI18N

        javax.swing.GroupLayout panelPrincipalTopLayout = new javax.swing.GroupLayout(panelPrincipalTop);
        panelPrincipalTop.setLayout(panelPrincipalTopLayout);
        panelPrincipalTopLayout.setHorizontalGroup(
            panelPrincipalTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalTopLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalTopLayout.setVerticalGroup(
            panelPrincipalTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panelPrincipalBody.setBackground(new java.awt.Color(255, 255, 255));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0,60));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(70, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0,60));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnRegistrar.setMaximumSize(new java.awt.Dimension(170, 35));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(170, 35));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        btnRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegistrarKeyPressed(evt);
            }
        });

        boxEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxEmpresaKeyPressed(evt);
            }
        });

        boxTipoSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoSeguroActionPerformed(evt);
            }
        });
        boxTipoSeguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxTipoSeguroKeyPressed(evt);
            }
        });

        txtNumeroPoliza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroPolizaKeyPressed(evt);
            }
        });

        txtDominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDominioActionPerformed(evt);
            }
        });
        txtDominio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDominioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDominioKeyTyped(evt);
            }
        });

        boxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProvinciaActionPerformed(evt);
            }
        });
        boxProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxProvinciaKeyPressed(evt);
            }
        });

        boxLocalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxLocalidadKeyPressed(evt);
            }
        });

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        txtNroDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroDireccionKeyTyped(evt);
            }
        });

        txtNroDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroDNIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroDNIKeyTyped(evt);
            }
        });

        radioBtnFemenino.setText("Femenino");
        radioBtnFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemeninoActionPerformed(evt);
            }
        });
        radioBtnFemenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                radioBtnFemeninoKeyPressed(evt);
            }
        });

        radioBtnMasculino.setText("Masculino");
        radioBtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMasculinoActionPerformed(evt);
            }
        });
        radioBtnMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                radioBtnMasculinoKeyPressed(evt);
            }
        });

        radioBtnOtros.setText("Otros");
        radioBtnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnOtrosActionPerformed(evt);
            }
        });
        radioBtnOtros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                radioBtnOtrosKeyPressed(evt);
            }
        });

        rSDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        rSDateChooser.setColorBackground(new java.awt.Color(153, 0, 0));
        rSDateChooser.setColorButtonHover(new java.awt.Color(153, 0, 0));
        rSDateChooser.setColorForeground(new java.awt.Color(0, 0, 0));
        rSDateChooser.setPlaceholder("FECHA DE NACIMIENTO");
        rSDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rSDateChooserKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalBodyLayout = new javax.swing.GroupLayout(panelPrincipalBody);
        panelPrincipalBody.setLayout(panelPrincipalBodyLayout);
        panelPrincipalBodyLayout.setHorizontalGroup(
            panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                        .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNroDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                                .addComponent(radioBtnFemenino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rSDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                        .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtApellido)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(boxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxLocalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumeroPoliza)
                                .addComponent(boxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDominio)
                                .addComponent(boxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
            .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPrincipalBodyLayout.setVerticalGroup(
            panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                        .addComponent(boxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalBodyLayout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDominio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNroDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioBtnFemenino)
                        .addComponent(radioBtnMasculino)
                        .addComponent(radioBtnOtros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(panelPrincipalBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addComponent(panelPrincipalBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addComponent(panelPrincipalTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrincipalBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped

    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here
        abm.setFormularioRegistrarCliente(this);
        if (abm.ejecutarRegistrar()) {
            principalCliente.getTablaCliente().setEstadoConsulta(0);
            principalCliente.getTablaCliente().ejecutarRellenarTabla();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        OperacionesUtiles.mensajeCancelarFormulario(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDominioActionPerformed

    private void txtDominioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDominioKeyTyped

    }//GEN-LAST:event_txtDominioKeyTyped
    InterfazGraficaFormularioRegistrarCliente interfazGraficaFormularioRegistrarCliente = new InterfazGraficaFormularioRegistrarCliente();
    private void boxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProvinciaActionPerformed
        interfazGraficaFormularioRegistrarCliente.setBoxProvincia(boxProvincia);
        interfazGraficaFormularioRegistrarCliente.setBoxLocalidad(boxLocalidad);
        interfazGraficaFormularioRegistrarCliente.evaluarEstadoConsultaLocalidad();
    }//GEN-LAST:event_boxProvinciaActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void boxTipoSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoSeguroActionPerformed
        if (this.boxTipoSeguro.getSelectedItem().equals("Automóvil") || this.boxTipoSeguro.getSelectedItem().equals("Motos")
                || this.boxTipoSeguro.getSelectedItem().equals("Camion") || this.boxTipoSeguro.getSelectedItem().equals("Camioneta")) {
            this.txtDominio.setEnabled(true);
        } else {
            this.txtDominio.setEnabled(false);
            this.txtDominio.setText("");
        }
    }//GEN-LAST:event_boxTipoSeguroActionPerformed

    private void txtNroDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroDireccionKeyTyped

    private void txtNroDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDNIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroDNIKeyTyped

    private void radioBtnFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemeninoActionPerformed
        if (this.getRadioBtnFemenino().isSelected()) {
            this.getRadioBtnMasculino().setSelected(false);
            this.getRadioBtnOtros().setSelected(false);
        }
    }//GEN-LAST:event_radioBtnFemeninoActionPerformed

    private void radioBtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMasculinoActionPerformed
        if (this.getRadioBtnMasculino().isSelected()) {
            this.getRadioBtnFemenino().setSelected(false);
            this.getRadioBtnOtros().setSelected(false);
        }
    }//GEN-LAST:event_radioBtnMasculinoActionPerformed

    private void radioBtnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnOtrosActionPerformed
        if (this.getRadioBtnOtros().isSelected()) {
            this.getRadioBtnFemenino().setSelected(false);
            this.getRadioBtnMasculino().setSelected(false);
        }
    }//GEN-LAST:event_radioBtnOtrosActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        new TecladoInterfaz().desplazar(evt, this.btnCancelar, this.txtApellido);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtNombre, this.txtTelefono);
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtApellido, this.boxProvincia);
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void boxProvinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxProvinciaKeyPressed
        new TecladoInterfaz().desplazarBox(evt, this.boxLocalidad);
       
    }//GEN-LAST:event_boxProvinciaKeyPressed

    private void boxLocalidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxLocalidadKeyPressed
        new TecladoInterfaz().desplazarBox(evt, this.txtDireccion);
    }//GEN-LAST:event_boxLocalidadKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtTelefono, this.txtNroDireccion);
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtNroDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDireccionKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtDireccion, this.boxEmpresa);
    }//GEN-LAST:event_txtNroDireccionKeyPressed

    private void boxEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxEmpresaKeyPressed
        new TecladoInterfaz().desplazarBox(evt, this.boxTipoSeguro);
    }//GEN-LAST:event_boxEmpresaKeyPressed

    private void txtNumeroPolizaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroPolizaKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtNroDireccion, this.txtDominio);
    }//GEN-LAST:event_txtNumeroPolizaKeyPressed

    private void txtDominioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDominioKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtNumeroPoliza, this.txtNroDNI);
    }//GEN-LAST:event_txtDominioKeyPressed

    private void txtNroDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDNIKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtDominio, this.rSDateChooser);
    }//GEN-LAST:event_txtNroDNIKeyPressed

    private void rSDateChooserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSDateChooserKeyPressed
        new TecladoInterfaz().desplazar(evt, this.txtNroDNI, this.radioBtnFemenino);
    }//GEN-LAST:event_rSDateChooserKeyPressed

    private void radioBtnFemeninoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioBtnFemeninoKeyPressed
        new TecladoInterfaz().desplazarBtn(evt, this.rSDateChooser, this.radioBtnMasculino, this.btnRegistrar, this.radioBtnOtros);
    }//GEN-LAST:event_radioBtnFemeninoKeyPressed

    private void radioBtnMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioBtnMasculinoKeyPressed
        new TecladoInterfaz().desplazarBtn(evt, this.rSDateChooser, this.radioBtnOtros, this.btnRegistrar, this.radioBtnFemenino);
    }//GEN-LAST:event_radioBtnMasculinoKeyPressed

    private void radioBtnOtrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioBtnOtrosKeyPressed
        new TecladoInterfaz().desplazarBtn(evt, this.rSDateChooser, this.radioBtnFemenino, this.btnRegistrar, this.radioBtnMasculino);
    }//GEN-LAST:event_radioBtnOtrosKeyPressed

    private void btnRegistrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistrarKeyPressed
        new TecladoInterfaz().desplazar(evt, this.radioBtnFemenino, this.btnCancelar);
    }//GEN-LAST:event_btnRegistrarKeyPressed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        new TecladoInterfaz().desplazar(evt, this.btnRegistrar, this.txtNombre);
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void boxTipoSeguroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxTipoSeguroKeyPressed
       new TecladoInterfaz().desplazarBox(evt, this.txtNumeroPoliza);
    }//GEN-LAST:event_boxTipoSeguroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioRegistrarCliente dialog = new FormularioRegistrarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JComboBox<String> getBoxEmpresa() {
        return boxEmpresa;
    }

    public void setBoxEmpresa(JComboBox<String> boxEmpresa) {
        this.boxEmpresa = boxEmpresa;
    }

    public JComboBox<String> getBoxLocalidad() {
        return boxLocalidad;
    }

    public void setBoxLocalidad(JComboBox<String> boxLocalidad) {
        this.boxLocalidad = boxLocalidad;
    }

    public JComboBox<String> getBoxProvincia() {
        return boxProvincia;
    }

    public void setBoxProvincia(JComboBox<String> boxProvincia) {
        this.boxProvincia = boxProvincia;
    }

    public JComboBox<String> getBoxTipoSeguro() {
        return boxTipoSeguro;
    }

    public void setBoxTipoSeguro(JComboBox<String> boxTipoSeguro) {
        this.boxTipoSeguro = boxTipoSeguro;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public JTextField getTxtDominio() {
        return txtDominio;
    }

    public void setTxtDominio(JTextField txtDominio) {
        this.txtDominio = txtDominio;
    }

    public JTextField getTxtNroDireccion() {
        return txtNroDireccion;
    }

    public void setTxtNroDireccion(JTextField txtNroDireccion) {
        this.txtNroDireccion = txtNroDireccion;
    }

    public JTextField getTxtNumeroPoliza() {
        return txtNumeroPoliza;
    }

    public void setTxtNumeroPoliza(JTextField txtNumeroPoliza) {
        this.txtNumeroPoliza = txtNumeroPoliza;
    }

    public MaterialButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(MaterialButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public MaterialButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(MaterialButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public RSDateChooser getrSDateChooser() {
        return rSDateChooser;
    }

    public void setrSDateChooser(RSDateChooser rSDateChooser) {
        this.rSDateChooser = rSDateChooser;
    }

    public JTextField getTxtNroDNI() {
        return txtNroDNI;
    }

    public void setTxtNroDNI(JTextField txtNroDNI) {
        this.txtNroDNI = txtNroDNI;
    }

    public JRadioButton getRadioBtnFemenino() {
        return radioBtnFemenino;
    }

    public void setRadioBtnFemenino(JRadioButton radioBtnFemenino) {
        this.radioBtnFemenino = radioBtnFemenino;
    }

    public JRadioButton getRadioBtnMasculino() {
        return radioBtnMasculino;
    }

    public void setRadioBtnMasculino(JRadioButton radioBtnMasculino) {
        this.radioBtnMasculino = radioBtnMasculino;
    }

    public JRadioButton getRadioBtnOtros() {
        return radioBtnOtros;
    }

    public void setRadioBtnOtros(JRadioButton radioBtnOtros) {
        this.radioBtnOtros = radioBtnOtros;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEmpresa;
    private javax.swing.JComboBox<String> boxLocalidad;
    private javax.swing.JComboBox<String> boxProvincia;
    private javax.swing.JComboBox<String> boxTipoSeguro;
    private principal.MaterialButton btnCancelar;
    private principal.MaterialButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelPrincipalBody;
    private javax.swing.JPanel panelPrincipalTop;
    private rojeru_san.componentes.RSDateChooser rSDateChooser;
    private javax.swing.JRadioButton radioBtnFemenino;
    private javax.swing.JRadioButton radioBtnMasculino;
    private javax.swing.JRadioButton radioBtnOtros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDominio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroDNI;
    private javax.swing.JTextField txtNroDireccion;
    private javax.swing.JTextField txtNumeroPoliza;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
